DROP DATABASE IF EXISTS culTourist_db;
-- Creates the "starter_db" database --
CREATE DATABASE culTourist_db;

USE culTourist_db;

CREATE TABLE users(
id INTEGER NOT NULL AUTO_INCREMENT,
full_name VARCHAR(30) NOT NULL,
numOfPosts INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE countries(
id INTEGER NOT NULL AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE posts(
id INTEGER NOT NULL AUTO_INCREMENT,
countryID INT NOT NULL,
userID INT NOT NULL,
title VARCHAR(30) NOT NULL,
body VARCHAR(255) NOT NULL,
category VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);